### ISSUE TITLE
Overall scheme of application / List of views

### ISSUE THREAD

**Issue by rdoo** [APMD/PMD#10]
Chciałbym zacząć coś robić w kwestii frontendu, ale do tego muszę wiedzieć jak ta aplikacja ma wyglądać. Przygotowałem listę proponowanych widoków do przedyskutowania:
- logowania
- rejestracji
- przypominania hasła
- główny widok listy filmów
- widok szczegółów danego filmu??
- upload pliku otrzymanego ze skryptu
- wklejenie samego tekstu ze skryptu (zamiast uploadu pliku?)
- lista filmów otrzymanych po przeprocesowaniu pliku do zaakceptowania przez usera
- dodawanie jakichś pojedynczych filmów do kolekcji??
- edycja profilu (hasło, nazwa użytkownika, email)

Tych widoków jest dość mało to zamiast dla każdego tworzyć osobną podstronę można też spróbować je wszystkie zmieścić na jednej głównej stronie (np. szczegóły filmu w popupie po najechaniu kursorem na dany film, do uploadu plików wystarczy jeden button, do dodawania pojedynczych plików jedno pole tekstowe gdzie wpisujemy tytuł i pod nim pojawia się mała lista proponowanych filmów).
Chciałbym więc wiedzieć jak wy to widzicie żeby ustalić jakąś wspólną koncepcję.

**Comment by jchmura** [comment]
Logowanie i rejestrację już mamy, nie musimy tego na razie przerabiać.
Przypomnienie hasła czy edycja profilu wydaje mi się na razie zbędna, są ważniejsze rzeczy w pierwszej kolejności. Interakcje między użytkownikami na razie nie robimy. Musimy najpierw dopracować single-player mode ;)

Najważniejszy jest widok listy filmów. Szczegóły filmu mogą być w popupie jak mówisz, dobry pomysł.

Uzgodniliśmy, że na razie akceptujemy tylko plik z outputem. Ale zastanawiam się, że może lepiej będzie mieć pole, do którego można ręcznie wkleić output, a wybierając plik jego treść sama się tam wrzuci. W ten sposób do backendu wystarczy wysyłać string (ten output), nie będzie się trzeba dodatkowo bawić w odbieranie plików.

Akceptowanie filmów było fajne. Ale to chyba nie powinno być na tej samej stronie, na której wyświetlane są już dodane filmy, bo może prowadzić do pomieszania. No chyba, że to będzie w jakimś modalu, wtedy ciężko się pomylić.

Dodawanie pojedynczych filmów może być fajne. Lecz na razie bym się za to nie brał. Musimy w ogóle  czy wrzucając nowy output lista filmów ma być nadpisywana czy nowe pozycje mają być do niej dodawane.
